title: Lawrence Sanares
logo: /assets/img/LS_headshot_circle.PNG
description:AI Product Architect and AI Business Strategy Lead. I design AI-powered products that solve real business challenges and improve decision-making. I bridge the gap between business strategy and AI technology by translating complex concepts into practical, business-focused solutions.
#show_downloads: true
#theme type: minimal | architect | cayman | dinky | hacker | minima | modernist
theme: jekyll-theme-minimal
github:
  is_project_page: false


