title: Lawrence Sanares
logo: /assets/img/LS_headshot_circle.PNG
description: <iframe src="https://www.slideshare.net/slideshow/embed_code/key/bof1pSJU9JiUQn?hostedIn=slideshare&page=upload" width="476" height="400" frameborder="0" marginwidth="0" marginheight="0" scrolling="no"></iframe>
#show_downloads: true
#theme type: minimal | architect | cayman | dinky | hacker | minima | modernist
theme: jekyll-theme-minimal
github:
  is_project_page: false


