title: Lawrence Sanares
logo: /assets/img/LS_headshot_circle.PNG
#description: text below image
#show_downloads: true
theme: jekyll-theme-minimal
<object data="the.pdf" width="1000" height="1000" type='application/pdf'/>
github:
  is_project_page: false


